---
# tasks file for worker
- name: Reset Cluster
  command: "{{ item }}"
  with_items:
    - kubeadm reset -f

- name: Remove /root/.kube
  file:
    path: /root/.kube
    state: absent

- name: Get token/endpoint/cacerthash for node-kubeadm.yml
  local_action:
    module: shell
    cmd: awk '{printf "%s\n%s\n%s",$3,$5,$7}' join-command
  register: tokenvar

- name: Get local dns name for aws hosts
  uri:
    url: http://169.254.169.254/latest/meta-data/local-hostname
    return_content: yes
  register: hostname
  failed_when: hostname.status != 200

- name: Generate node-kubeadm.yml
  vars:
    - token: "{{ tokenvar.stdout_lines[1] }}"
    - endpoint: "{{ tokenvar.stdout_lines[0] }}"
    - cacerthash: "{{ tokenvar.stdout_lines[2] }}" 
    - node_FQDN: "{{ hostname.content }}"
  template:
    src: kubeadm_node_join.yml.j2
    dest: /tmp/node-kubeadm.yml

- name: Join cluster
  shell: kubeadm join --config=/tmp/node-kubeadm.yml
