---
# tasks file for master
- name: Get private ip for aws hosts
  uri:
    url: http://169.254.169.254/latest/meta-data/local-ipv4
    return_content: yes
  register: ipv4
  failed_when: ipv4.status != 200

- name: Copy kubeadm config to controlplane
  template:
    src: kubeadm-init.yaml.j2
    dest: "{{ kubeadm_config_dest }}"
    mode: '0644'
  vars:
    - private_ipv4: "{{ ipv4.content }}"

- name: Initialize kubernetes cluster using the kubeadm config
  command: kubeadm init --config {{ kubeadm_config_dest }} --upload-certs

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- name: Get the certificate for other controlplane (cert valid for 2 hours)
  command: kubeadm init phase upload-certs --upload-certs
  register: join_cert

- name: copy certificate to local file
  become: false
  local_action: copy content="{{ join_cert.stdout_lines[2] }}" dest="./join-cert"

- name: Fetch admin.conf to host
  fetch: 
    src: /etc/kubernetes/admin.conf
    dest: ./kubeconfig.yml
    flat: true
