---
- hosts: nodeAll
  become: yes
  tasks:
  - name: set hostname match to the dns name in private net
    block:
    - name: Get FQDN for aws host in private net
      uri:
        url: http://169.254.169.254/latest/meta-data/local-hostname
        return_content: yes
      register: hostname
      failed_when: hostname.status != 200

    - name: update domain name
      shell: hostnamectl set-hostname {{ hostname.content }}
