---
- hosts: localhost
  gather_facts: no
  become: yes

  tasks:
  - name: Install kubectl
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      mode: '0755'

  - name: Get helm
    get_url:
      url: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
      dest: /tmp/
      checksum: "sha256:018f9908cb950701a5d59e757653a790c66d8eda288625dbb185354ca6f41f6b"

  - name: unarchive helm
    unarchive:
      remote_src: yes
      src: /tmp/helm-v3.2.1-linux-amd64.tar.gz
      dest: /tmp

  - name: move helm binaries to PATH
    become: yes
    copy:
      remote_src: yes
      src: /tmp/linux-amd64/helm 
      dest: /usr/local/bin/helm
      mode: "0755"
