---
# for the first master
- hosts: cp1
  become: yes

  tasks:
  - name: prepare first master node
    import_role:
      name: master1
    vars:
    - kubeadm_config_dest: "/tmp/kubeadm-init.yml"

  - debug:
      msg: "run the command in your shell to connect to the k8s cluster: export KUBECONFIG=`pwd`/kubeconfig.yml"
