---
- hosts: localhost
  gather_facts: no
  become: no

  tasks:
  - name: Install CNI/StorageClass/LoadBalancer
    import_role:
      name: k8s
    vars:
      - aws_region: ap-southeast-1
      - kubeconfig: /vagrant/ansible/kubeconfig.yml
