---
- hosts: localhost
  become: no
  gather_facts: no
  tasks:
  # - name: Install Ingress Controller
  #   command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/aws/deploy.yaml
  #   environment: 
  #     KUBECONFIG: ./kubeconfig.yml
  - name: mkdir deploy
    file:
      path: ./deploy_cache
      state: directory

  - name: Get ingress-nginx controller definition
    get_url:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/aws/deploy.yaml
      dest: ./deploy_cache/nginx-ingress-controller-0_32_0.yaml
      mode: '0644'

  - name: Deploy Ingress Controller
    k8s:
      apply: yes
      src: ./deploy_cache/nginx-ingress-controller-0_32_0.yaml
      kubeconfig: ./kubeconfig.yml

  - debug:
      msg:
      - "Please wait a few minutes for AWS to generate an Network Load Balancer (NLB),"
      - "if you want to generate an Ingress resource."
