---
- hosts: nodeAll
  gather_facts: no
  become: no

  tasks:
  - name: run ssh-gen to remove ssh fingerprints from ~/.ssh/known_hosts
    local_action: command ssh-keygen -f ~/.ssh/known_hosts -R {{ hostvars[inventory_hostname]['ansible_host'] }}
    changed_when: True  # probably no need to check
