---
# tasks file for k8s
- name: Install calico CNI
  command: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

  # For other CNI (may need to change the podSubnet in `templates/aws.yml.j2`)
  # shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  # command: kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.6/install/kubernetes/quick-install.yaml
  # command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Deploy standard storageClass
  k8s:
    state: present
    definition:
      kind: StorageClass
      apiVersion: storage.k8s.io/v1beta1
      metadata:
        name: standard
      provisioner: kubernetes.io/aws-ebs
      parameters:
        type: gp2
    apply: yes
    kubeconfig: "{{ kubeconfig }}"

- name: Deploy standard storageClass for first AZ
  k8s:
    state: present
    definition:
      kind: StorageClass
      apiVersion: storage.k8s.io/v1beta1
      metadata:
        name: standard-a
      provisioner: kubernetes.io/aws-ebs
      parameters:
        type: gp2
      allowedTopologies:
      - matchLabelExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          values:
          - "{{ aws_region }}a"
    apply: yes
    kubeconfig: "{{ kubeconfig }}"

- name: Install ingress-nginx controller
  block:
  - name: mkdir cache folder for definition file
    file:
      path: ./deploy_cache
      state: directory

  - name: Get ingress-nginx controller definition
    get_url:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/aws/deploy.yaml
      dest: ./deploy_cache/nginx-ingress-controller.yaml
      mode: '0644'

  - name: Deploy Ingress Controller
    k8s:
      apply: yes
      src: ./deploy_cache/nginx-ingress-controller.yaml
      kubeconfig: "{{ kubeconfig }}"

# In some scenarios is required to terminate TLS in the Load Balancer and not in the ingress controller.
# see https://kubernetes.github.io/ingress-nginx/deploy/#tls-termination-in-aws-load-balancer-elb
# - name: Add TLS termination for NLB
#   block:
#   - name: Get ingress-nginx controller definition
#     get_url:
#       url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.35.0/deploy/static/provider/aws/deploy-tls-termination.yaml
#       dest: ./deploy_cache/deploy-tls-termination.yaml
#       mode: '0644'

#   - name: edit the file
#     lineinfile:
#       path: ./deploy_cache/deploy-tls-termination.yaml
#       regexp: '  proxy-real-ip-cidr:.*'
#       line: '  proxy-real-ip-cidr: YYY.YYY.YYY/YY'

#   - name: edit the file
#     lineinfile:
#       path: ./deploy_cache/deploy-tls-termination.yaml
#       regexp: '    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:.*'
#       line: '    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:YYYYYYYY:certificate/YYYYYY-YYYYYYY-YYYYYYY-YYYYYYYY'

#   - name: Deploy TLS termination
#     k8s:
#       apply: yes
#       src: ./deploy_cache/deploy-tls-termination.yaml
#       kubeconfig: "{{ kubeconfig }}"
#

